version: '3.5'

networks:
  intemporal:

services:

  mariadb:
    image: bitnami/mariadb:10.6.11
    networks:
      - intemporal
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_ROOT_USER: root
      MARIADB_DATABASE: root
      MARIADB_SKIP_TEST_DB: "true"
      MARIADB_ENABLE_SLOW_QUERY: "true"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - 3306:3306
