name: Clojure CI

#on: [push, pull_request]
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache nodejs dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: nodedeps-${{ hashFiles('package-lock.json') }}
          restore-keys: nodedeps-


      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.0
        with:
          # Install just one or all simultaneously
          # The value must indicate a particular version of the tool, or use 'latest'
          # to always provision the latest version
          cli: 1.10.1.693              # Clojure CLI based on tools.deps
          clj-kondo: 2022.05.31        # Clj-kondo
          cljstyle: 0.15.0             # cljstyle

      # requires clojure
      - name: compile cljs
        run: npx shadow-cljs compile dev

      # will cache shadow deps too
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Lint and test clj
        run: bin/kaocha unit

      - name: Lint and test cljs
        run: bin/kaocha unit-cljs

      - name: install node deps
        run: npm install
